# Generated by Django 5.2.1 on 2025-05-27 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Название')),
                ('game_url', models.URLField(default='', max_length=250, verbose_name='Ссылка на игру')),
                ('description', models.CharField(default='', max_length=160, verbose_name='Описание')),
                ('thumbnail', models.URLField(default='', max_length=250, verbose_name='Url иконки')),
                ('genre', models.URLField(default='', max_length=30, verbose_name='Жанр')),
                ('date', models.DateField(default=datetime.date(2020, 10, 15), verbose_name='Дата разработки')),
            ],
        ),
    ]
