# Generated by Django 5.2.1 on 2025-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160, verbose_name='Описание')),
                ('thumbnail', models.CharField(verbose_name='Url иконки')),
            ],
        ),
    ]
