# Generated by Django 5.2.1 on 2025-05-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='thumbnail',
            field=models.CharField(max_length=250, verbose_name='Url иконки'),
        ),
    ]
