# Generated by Django 5.2.1 on 2025-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_games_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_url',
            field=models.URLField(default='', max_length=250, verbose_name='Ссылка на игру'),
        ),
        migrations.AddField(
            model_name='games',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.CharField(default='', max_length=160, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='games',
            name='thumbnail',
            field=models.URLField(default='', max_length=250, verbose_name='Url иконки'),
        ),
    ]
