# Generated by Django 5.2.1 on 2025-05-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_games_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
