# Generated by Django 5.2.1 on 2025-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_games_game_url_games_title_alter_games_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.URLField(default='', max_length=30, verbose_name='Жанр'),
        ),
    ]
